### ISSUE TITLE
payment_id - not have any information for miners

### ISSUE THREAD

**Issue by sflyer** [clintar/cryptonote-xmr-pool#11]
Hello!
I'm trying to configure the pool and found it with a problem. If i try mining with payment_id in admin panel dont see any information about mining. In "Your Stats & Payment History" enter wallet.payment_id - not found.
But miner working and in a log file message:
2017-07-10 10:41:09 [pool] (Thread 1) Miner connected 44eQFpU8QW9hz7Sn9o1so1LuAQatLA7jHCBMdWqHjaieTSULvGTjv5ianmqYYwUC1i6e6mXPNLMpXaNzAZWj7Rvo8nd3KQd.cf8447bb6d2b419759dba6d0707c7e4a34460f67bd66cb90c45c3359cd22b4da@192.168.0.111`
Tell me, is it necessary to specify a payment_id(i mean not wallet.payment_id) in another way in the program or not such an opportunity?

And sorry for google translate :)

**Comment by clintar** [comment]
payment_id isn't supported by this pool code. i haven't tried to get the bbr payment_id code working in this

**Comment by sflyer** [comment]
Thanks for the answer. You can tell the pool code, which supports this functionality, I will be grateful for help
