### ISSUE TITLE
SSL on pool

### ISSUE THREAD

**Issue by sflyer** [clintar/cryptonote-xmr-pool#12]
Hi!
My configuration:
Nginx + ubuntu 16.04
Firewall: disabled

In the nginx configuration, I added an ssl certificate, after which I can not connect to the API.
In the pool settings (config.json):
1) included ssl
2) changed the path to the certificate

If I switch to WE-IP: 8119 - I see the API the same way as the version without SSL. There are no errors in the log file. But web pages do not connect to the API.
Please help me, what am I doing wrong?

**Comment by clintar** [comment]
Got it working?
