### ISSUE TITLE
npm update too slow

### ISSUE THREAD

**Issue by ChangedenCZD** [clintar/cryptonote-xmr-pool#29]
npm update too slow

**Comment by brandon-dacrib** [comment]
npm update being slow would bot be the fault of this program this is not an issue that belongs here.

**Comment by brandon-dacrib** [comment]
this takes under 2 minutes in a container on my laptop
real	1m9.689s
user	0m38.510s
sys	0m3.290s

Translating source code into a machine executable binary code tends to take a bit of work. You would not want to do this by hand.

**Comment by clintar** [comment]
Not an issue I can address
