### ISSUE TITLE
Is this compatible with Monero 0.10.3.1

### ISSUE THREAD

**Issue by c789** [clintar/cryptonote-xmr-pool#9]

**Comment by clintar** [comment]
maybe! i haven't tested it

**Comment by c789** [comment]
I installed it and it is accepting shares, so all seems well.

**Comment by clintar** [comment]
If there are changes with blocks, it could still fail. I haven't looked into the changes

**Comment by EvilCodingMonkey** [comment]
I can confirm that it works perfectly with 0.10.3.1. Thanks for your excellent work by the way!

**Comment by clintar** [comment]
Yay, glad it still works! Thanks for your verfication.
